name: mnist~200~200-nvil_lr1e-4_wd1e-3
dataset: mnist
binarize_online: true
iteration: 500_000

inference_net:
    type: nonlinear
    units: [[784, 200], [200, 200]]
    optimizer:
        method: adam
        alpha: 0.0001
        weight_decay: 0.001

generative_net:
    type: nonlinear
    units: [[200, 784], [200, 200]]
    optimizer:
        method: adam
        alpha: 0.0001
        weight_decay: 0.001

estimator:
    method: likelihood_ratio
    use_baseline_model: true
    normalize_variance: true
    n_samples: 400
    optimizer:
        method: adam
        alpha: 0.0001
        weight_decay: 0.001
