name: mnist-200-200-nvil_lr1e-3_wd0
dataset: mnist
binarize_online: true
iteration: 500_000

inference_net:
    type: linear
    units: [200, 200]
    optimizer:
        method: adam
        alpha: 0.001
        weight_decay: 0.

generative_net:
    type: linear
    units: [784, 200]
    optimizer:
        method: adam
        alpha: 0.001
        weight_decay: 0.

estimator:
    method: likelihood_ratio
    use_baseline_model: true
    normalize_variance: true
    n_samples: 400
    optimizer:
        method: adam
        alpha: 0.001
        weight_decay: 0.
