name: $dataset-deep-leg#batch_size=$batch_size-decay=$decay-lr=$lr-n_samples=$n_samples
dataset: $dataset
batch_size: $batch_size
eval_batch_size: $batch_size
binarize_online: true
iteration: 2_000_000

inference_net:
    type: linear
    units: [[784, 200], [200, 200], [200, 200], [200, 200]]
    optimizer:
        method: rmsprop
        lr: $lr
        weight_decay: $decay

generative_net:
    type: linear
    units: [[200, 784], [200, 200], [200, 200], [200, 200]]
    optimizer:
        method: rmsprop
        lr: $lr
        weight_decay: $decay

estimator:
    method: local_expectation_gradient
    optimizer:
        method: rmsprop
        lr: $lr
        weight_decay: $decay
